AnimalsMVC/Models/Animal.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AnimalsMVC.Models
{
    /// <summary>
    /// Класс для описания животного.
    /// </summary>
    public class Animal
    {
        [Key]
        public long Id { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        public long TypeId { get; set; }

        [Required]
        public long ColorId { get; set; }

        [Required]
        public long LocationId { get; set; }

        [ForeignKey("TypeId")]
        public virtual AnimalType Type { get; set; }

        [ForeignKey("ColorId")]
        public virtual SkinColor Color { get; set; }

        [ForeignKey("LocationId")]
        public virtual Location Location { get; set; }
    }
}

AnimalsMVC/Models/AnimalType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
using System.ComponentModel.DataAnnotations;

namespace AnimalsMVC.Models
{
    /// <summary>
    /// Класс для описания типа животного.
    /// </summary>
    public class AnimalType
    {
        [Key]
        public long Id { get; set; }

        public string Name { get; set; }
    }
}

AnimalsMVC/Models/Location.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AnimalsMVC.Models
{
    /// <summary>
    /// Класс для описания области обитания.
    /// </summary>
    public class Location
    {
        [Key]
        public long Id { get; set; }

        public string Name { get; set; }

        public long RegionId { get; set; }

        [ForeignKey("RegionId")]
        public virtual Region Region { get; set; }
    }
}

AnimalsMVC/Models/Region.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
namespace AnimalsMVC.Models
{
    /// <summary>
    /// Класс для описания региона.
    /// </summary>
    public class Region
    {
        [Key]
        public long Id { get; set; }

        public string Name { get; set; }
    }
}

AnimalsMVC/Models/SkinColor.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace AnimalsMVC.Models
{
    /// <summary>
    /// Класс для описания цвета шкуры.
    /// </summary>
    public class SkinColor
    {
        [Key]
        public long Id { get; set; }

        public string Name { get; set; }
    }
}

AnimalsMVC/Controllers/ZooController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AnimalsMVC.Infrastructure;
using AnimalsMVC.Models;

namespace AnimalsMVC.Controllers
{
    public class ZooController : Controller
    {
        private AnimalsRepository _repo;

        public ZooController()
        {
            _repo = new AnimalsRepository(new ZooContext());
        }

        /// <summary>
        /// Главная страница с каталогом.
        /// </summary>
        /// <returns></returns>
        public ActionResult Catalog()
        {
            return View();
        }

        /// <summary>
        /// Страница добавления новой записи.
        /// </summary>
        /// <returns></returns>
        public ActionResult AddAnimal()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddAnimal(Animal model)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("msg-error", "Model validation error.");
                return View();
            }

            try
            {
                var item = _repo.AddAnimal(model);
            }
            catch (Exception)
            {
                ModelState.AddModelError("msg-error", "Operation error. Please, try again later.");
                return View();
            }

            return RedirectToAction("Catalog");
        }

        /// <summary>
        /// Получение записи о животном.
        /// </summary>
        /// <param name="animalId">ID записи.</param>
        /// <returns></returns>
        public PartialViewResult GetAnimalAjax(long animalId)
        {
            var record = _repo.GetAnimal(animalId);

            return PartialView("_UpdateAnimal", record);
        }
        
        /// <summary>
        /// Обновить содержимое записи.
        /// </summary>
        /// <param name="model">Объект обновления.</param>
        /// <returns></returns>
        [HttpPost]
        public PartialViewResult UpdateAnimal(Animal model)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("msg-error", "Model validation error.");
            }

            try
            {
                _repo.UpdateAnimal(model);
                ModelState.AddModelError("msg-success", "Updated successfully.");
            }
            catch (Exception)
            {
                ModelState.AddModelError("msg-error", "Model updating error.");
            }

            return PartialView("_UpdateAnimal");
        }

        /// <summary>
        /// Загрузка данных в таблицу.
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public JsonResult LoadTableContentAjax()
        {
            if (!Request.IsAjaxRequest())
                return Json("request_type_error", JsonRequestBehavior.AllowGet);
            
            // построить сигнатуру
            var tableRequestData = AnimalsTableHandler.ExtractData(Request);

            // запросить данные по сигнатуре
            var found = _repo.GetAnimals(
                tableRequestData.OrderByNameAsc,
                tableRequestData.TypeFilter,
                tableRequestData.ColorFilter,
                tableRequestData.RegionFilter
                );

            // число выбранных/пропущенных записей
            int takeCount = tableRequestData.Length;
            int skipCount = tableRequestData.Start;

            // форматировать данные для вывода в js-таблице
            var foundFormatted = found.Select(
                x => new
                {
                    id = x.Id,
                    name = x.Name,
                    type = x.Type.Name,
                    color = x.Color.Name,
                    location = x.Location.Name,
                    region = x.Location.Region.Name,
                }).Skip(skipCount).Take(takeCount).ToArray();

            // сформировать ответную сигнатуру
            var tableResponseData = new {
                data = foundFormatted,
                draw = tableRequestData.Draw,
                start = tableRequestData.Start,
                length = tableRequestData.Length,
                recordsTotal = _repo.GetAnimals().Count(),
                recordsFiltered = found.Count()
            };

            return Json(tableResponseData, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Удаление выбранной записи.
        /// </summary>
        /// <param name="animalId">ID записи.</param>
        /// <returns></returns>
        public ActionResult RemoveAnimalAjax(long animalId)
        {
            if (animalId == 0)
                return Json(false, JsonRequestBehavior.AllowGet);

            try
            {
                _repo.RemoveAnimal(animalId);
                return Json(true, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {
                return Json(false, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

AnimalsMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/dt-css")
    <link href="~/favicon.ico" type="image/x-icon" rel="shortcut icon" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Zoo Catalog", "Catalog", "Zoo", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jquery-uo")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/chosen")
    @Scripts.Render("~/bundles/dt")
    @Scripts.Render("~/bundles/dt-filters")
    @Scripts.Render("~/bundles/custom")
    @RenderSection("scripts", required: false)
</body>
</html>

AnimalsMVC/Views/Zoo/AddAnimal.cshtml
@model AnimalsMVC.Models.Animal
@{
    var types = AnimalsMVC.Infrastructure.AnimalDetailsHelper.GetAnimalTypes();
    var colors = AnimalsMVC.Infrastructure.AnimalDetailsHelper.GetSkinColors();
    var locations = AnimalsMVC.Infrastructure.AnimalDetailsHelper.GetAnimalLocations();
}

<div class="common-header">
    <h2>Добавление записи о животном</h2>
</div>

<div class="common-container">
    @using (Html.BeginForm("AddAnimal", "Zoo", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        @Html.AntiForgeryToken()
        <div class="container-fluid">
            <div class="form-group">
                <label for="formGroupInputLarge1" class="col-sm-2 control-label">Наименование</label>
                <div class="col-sm-10">
                    @Html.TextBoxFor(m => m.Name, new { @class = "form-control", placeholder = "Полное название" })
                    @Html.ValidationMessageFor(m => m.Name, null, new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label for="formGroupInputLarge1" class="col-sm-2 control-label">Тип</label>
                <div class="col-sm-10">
                    <select name="TypeId" class="form-control">
                        <option>None</option>
                        @foreach (var item in types)
                        {
                            <option value="@item.Id">@item.Name</option>
                        }
                    </select>
                </div>
            </div>

            <div class="form-group">
                <label for="formGroupInputLarge1" class="col-sm-2 control-label">Цвет</label>
                <div class="col-sm-10">
                    <select name="ColorId" class="form-control">
                        <option>None</option>
                        @foreach (var item in colors)
                        {
                            <option value="@item.Id">@item.Name</option>
                        }
                    </select>
                </div>
            </div>

            <div class="form-group">
                <label for="formGroupInputLarge1" class="col-sm-2 control-label">Место обитания</label>
                <div class="col-sm-10">
                    <select name="LocationId" class="form-control">
                        <option>None</option>
                        @foreach (var item in locations)
                        {
                            <option value="@item.Id">@item.Name</option>
                        }
                    </select>
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-2">
                    <button type="submit" class="btn btn-success btn-lg">Сохранить</button>
                </div>
                <div class="col-sm-2">
                    @Html.ActionLink("Назад", "Catalog", null, new { @class = "btn btn-primary btn-lg" })
                </div>
            </div>
        </div>
    }
</div>

@if (ViewData.ModelState["msg-error"] != null && ViewData.ModelState["msg-error"].Errors.Count() > 0)
{
    <div class="alert alert-danger">
        <a class="close" data-dismiss="alert">×</a>
        <h5 class="alert-heading">Errors</h5>
        @Html.ValidationSummary(false)
    </div>
} 

AnimalsMVC/Views/Zoo/Catalog.cshtml
@{
    ViewBag.Title = "Каталог зверей";
}

<div class="common-header">
    <div class="well">
        <div class="composite-header">
            <div class="composite-header-1">
                <img src="~/Content/images/dte.png" class="img-responsive" alt="Dora" />
            </div>

            <div class="composite-header-2">
                <h1>Каталог зверей</h1>
            </div>

            <div class="composite-header-3">
                @Html.ActionLink("Добавить новое животное", "AddAnimal", null, new { @class = "btn btn-info btn-lg" })
            </div>
        </div>
    </div>
</div>

<div class="common-container zoo-table-outline">
    <div class="container-fluid">
        <table id="dt-animals" class="hover"></table>
    </div>
</div>

<!-- 'edit' animal modal -->
<div class="modal fade" tabindex="-1" role="dialog" id="modal-edit-animal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Редактирование записи</h4>
            </div>

            <div class="modal-body" id="hex">
                @Html.Partial("_UpdateAnimal")
            </div>
        </div>
    </div>
</div>

<!-- 'show' animal modal -->
<div class="modal fade" tabindex="-1" role="dialog" id="modal-show-animal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Информация о записи</h4>
            </div>

            <div class="modal-body" >
                <div class="container-fluid">
                    <div class="row">
                        <div class="input-group col-md-10">
                            <span class="input-group-addon" id="basic-addon1">Наименование</span>
                            <input type="text" class="form-control" id="info-animal-name" aria-describedby="basic-addon1" readonly>
                        </div>
                    </div>

                    <div class="row">
                        <div class="input-group col-md-10">
                            <span class="input-group-addon" id="basic-addon1">Тип</span>
                            <input type="text" class="form-control" id="info-animal-type" aria-describedby="basic-addon1" readonly>
                        </div>
                    </div>

                    <div class="row">
                        <div class="input-group col-md-10">
                            <span class="input-group-addon" id="basic-addon1">Цвет шкуры</span>
                            <input type="text" class="form-control" id="info-animal-color" aria-describedby="basic-addon1" readonly>
                        </div>
                    </div>

                    <div class="row">
                        <div class="input-group col-md-10">
                            <span class="input-group-addon" id="basic-addon1">Область обитания</span>
                            <input type="text" class="form-control" id="info-animal-location" aria-describedby="basic-addon1" readonly>
                        </div>
                    </div>
                </div>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть окно</button>
            </div>
        </div>
    </div>
</div>

AnimalsMVC/Views/Zoo/_UpdateAnimal.cshtml
@model AnimalsMVC.Models.Animal
@{ 
    var types = AnimalsMVC.Infrastructure.AnimalDetailsHelper.GetAnimalTypes().Select(x => new SelectListItem { Text = x.Name, Value = x.Id.ToString() });
    var colors = AnimalsMVC.Infrastructure.AnimalDetailsHelper.GetSkinColors().Select(x => new SelectListItem { Text = x.Name, Value = x.Id.ToString() });
    var locations = AnimalsMVC.Infrastructure.AnimalDetailsHelper.GetAnimalLocations().Select(x => new SelectListItem { Text = x.Name, Value = x.Id.ToString() });
}

@using (Ajax.BeginForm("UpdateAnimal", new { }, new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "hex", OnSuccess = "OnEditAnimalComplete" }))
{
    <div class="container-fluid">
        <div class="row">
            <div class="input-group">
                @Html.HiddenFor(m=>m.Id)
            </div>
            <div class="input-group col-md-10">
                <span class="input-group-addon" id="basic-addon1">Наименование</span>
                @Html.TextBoxFor(m => m.Name, null, new { @class = "form-control" })
            </div>
        </div>

        <div class="row">
            <div class="input-group col-md-10">
                <span class="input-group-addon" id="basic-addon1">Тип</span>
                @Html.DropDownListFor(m => m.TypeId, types, new { @class = "form-control" })
            </div>
        </div>

        <div class="row">
            <div class="input-group col-md-10">
                <span class="input-group-addon" id="basic-addon1">Цвет</span>
                @Html.DropDownListFor(m => m.ColorId, colors, new { @class = "form-control" })
            </div>
        </div>

        <div class="row">
            <div class="input-group col-md-10">
                <span class="input-group-addon" id="basic-addon1">Область обитания</span>
                @Html.DropDownListFor(m=>m.LocationId, locations, new { @class = "form-control"})
            </div>
        </div>

        <div class="row">
            <input type="submit" class="form-control btn-success" value="Сохранить" />
        </div>
    </div>
}

@if (ViewData.ModelState["msg-error"] != null && ViewData.ModelState["msg-error"].Errors.Count() > 0) 
{ 
   <div class="alert alert-danger"> 
      <a class="close" data-dismiss="alert">×</a> 
      <h5 class="alert-heading">Errors</h5> 
      @Html.ValidationSummary(false)
   </div>
} 

@if (ViewData.ModelState["msg-success"] != null && ViewData.ModelState["msg-success"].Errors.Count() > 0)
{
    <div class="alert alert-success">
        <a class="close" data-dismiss="alert">×</a>
        <h5 class="alert-heading">Result</h5>
        @Html.ValidationSummary(false)
    </div>
} 